### PR TITLE
Update Generator.py

### PR DESCRIPTION
**Pull request by CaptainStrannik**
secret in the end of file

### CODE REVIEW

**Comment by misha99fr** [comment]
UPDATE PLEASE

**Comment by NobootRecord** [comment]
Okay, I will ask MrErtor to update the program ;)

**Comment by NobootRecord** [comment]
I have decided to close this pull request without program updating. Sorry for that.

The last version of the program has rewritten and fixed GUI initialization code, and your submitted code has legacy code. If I apply them, the program will be broken and I will get a star pill (Russian "получить звездюлей") from TheErtor (original program author).
Also I have found nothing useful and/or interesting in this modified program code.

If having any questions, contact me on Discord: NobootRecord#2297
Or e-mail: nobootrecord at mail dot ru (anti-spam protection 9000 level lol)

**Comment by misha99fr** [comment]
OH NO

**Pull request closed without merging**
